package Codigo;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Component;
import javax.swing.JRadioButton;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import java.sql.DriverManager;
import java.sql.*;
import javax.swing.*;



/**
 *
 * @author fran
 */

public class Nueva extends javax.swing.JFrame {
    private ArrayList<javax.swing.JLabel> comp=new ArrayList();
    private int cont=0, promAr, promDef, promMed, promAta, formAr, formDef, formMed, formAta, roo=0;

    PlantillasDB pp = new PlantillasDB();
    public static String nteam="Testeo";


    /**
     * Creates new form Nueva
     */
    public Nueva() {
        initComponents();
        clean();
        //jug1.setVisible(false);
        ComponentMover cm = new ComponentMover();
        cm.registerComponent(jugElegido);        
        
        this.setTitle("Team Manager");
        jsH1.setPaintLabels(true);
        jsH2.setPaintLabels(true);
        jsH3.setPaintLabels(true);
        jsH4.setPaintLabels(true);
        
        jsH2.setPaintTicks(true);
        jsH1.setPaintTicks(true);
        jsH3.setPaintTicks(true);
        jsH4.setPaintTicks(true);
        
        jsH1.setMajorTickSpacing(25);
        jsH2.setMajorTickSpacing(25);
        jsH3.setMajorTickSpacing(25);
        jsH4.setMajorTickSpacing(25);
        comp.add(jug1);
        comp.add(jug2);
        comp.add(jug3);
        comp.add(jug4);
        comp.add(jug5);
        comp.add(jug6);
        comp.add(jug7);
        comp.add(jug8);
        comp.add(jug9);
        comp.add(jug10);
        comp.add(jug11);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jsH1 = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        txtH1 = new javax.swing.JLabel();
        jsH2 = new javax.swing.JSlider();
        txtH2 = new javax.swing.JLabel();
        jsH3 = new javax.swing.JSlider();
        txtH3 = new javax.swing.JLabel();
        txtH4 = new javax.swing.JLabel();
        jsH4 = new javax.swing.JSlider();
        btGuardar = new javax.swing.JButton();
        txtNombreEquipo = new javax.swing.JTextField();
        txtArquero = new javax.swing.JTextField();
        txtDefensa = new javax.swing.JTextField();
        txtMedio = new javax.swing.JTextField();
        txtAtaque = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jugElegido = new javax.swing.JLabel();
        jug1 = new javax.swing.JLabel();
        jug2 = new javax.swing.JLabel();
        jug3 = new javax.swing.JLabel();
        jug4 = new javax.swing.JLabel();
        jug5 = new javax.swing.JLabel();
        jug6 = new javax.swing.JLabel();
        jug7 = new javax.swing.JLabel();
        jug8 = new javax.swing.JLabel();
        jug9 = new javax.swing.JLabel();
        jug10 = new javax.swing.JLabel();
        jug11 = new javax.swing.JLabel();
        txtCanchita = new javax.swing.JLabel();
        btPlantilla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cabin", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/txtlogo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 370, 70));

        jButton1.setText("←");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 72, 51)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 30, 30));

        jsH1.setToolTipText("");
        jsH1.setValue(0);
        jsH1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsH1StateChanged(evt);
            }
        });
        getContentPane().add(jsH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 200, 42));

        jLabel3.setText("Nombre del jugador");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        txtH1.setText("Arquero");
        getContentPane().add(txtH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 120, -1));

        jsH2.setValue(0);
        jsH2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsH2StateChanged(evt);
            }
        });
        getContentPane().add(jsH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 200, 42));

        txtH2.setText("Defensa");
        getContentPane().add(txtH2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 120, -1));

        jsH3.setValue(0);
        jsH3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsH3StateChanged(evt);
            }
        });
        getContentPane().add(jsH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 200, 42));

        txtH3.setText("Mediocampo");
        getContentPane().add(txtH3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 119, -1));

        txtH4.setText("Ataque");
        getContentPane().add(txtH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 120, -1));

        jsH4.setValue(0);
        jsH4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jsH4StateChanged(evt);
            }
        });
        getContentPane().add(jsH4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 200, 42));

        btGuardar.setBackground(java.awt.Color.lightGray);
        btGuardar.setText("Guardar");
        btGuardar.setToolTipText("");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 130, 30));

        txtNombreEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEquipoActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombreEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 245, -1));

        txtArquero.setEditable(false);
        txtArquero.setText("0");
        txtArquero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArqueroActionPerformed(evt);
            }
        });
        getContentPane().add(txtArquero, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 35, -1));

        txtDefensa.setEditable(false);
        txtDefensa.setText("0");
        txtDefensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDefensaActionPerformed(evt);
            }
        });
        getContentPane().add(txtDefensa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 35, -1));

        txtMedio.setEditable(false);
        txtMedio.setText("0");
        txtMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedioActionPerformed(evt);
            }
        });
        getContentPane().add(txtMedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 35, -1));

        txtAtaque.setEditable(false);
        txtAtaque.setText("0");
        txtAtaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAtaqueActionPerformed(evt);
            }
        });
        getContentPane().add(txtAtaque, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, 35, -1));

        jLabel9.setText("Nombre del equipo");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 245, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 53, 854, 10));

        jPanel2.setLayout(null);

        jugElegido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jug.png"))); // NOI18N
        jPanel2.add(jugElegido);
        jugElegido.setBounds(370, 200, 28, 50);

        jug1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jugelegido.png"))); // NOI18N
        jug1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jug1);
        jug1.setBounds(500, 400, 130, 40);

        jug2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jugelegido.png"))); // NOI18N
        jug2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jug2);
        jug2.setBounds(500, 360, 130, 40);

        jug3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jugelegido.png"))); // NOI18N
        jug3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jug3);
        jug3.setBounds(500, 320, 130, 40);

        jug4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jugelegido.png"))); // NOI18N
        jug4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jug4);
        jug4.setBounds(500, 280, 130, 40);

        jug5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jugelegido.png"))); // NOI18N
        jug5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jug5);
        jug5.setBounds(500, 240, 130, 40);

        jug6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jugelegido.png"))); // NOI18N
        jug6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jug6);
        jug6.setBounds(500, 200, 130, 40);

        jug7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jugelegido.png"))); // NOI18N
        jug7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jug7);
        jug7.setBounds(500, 160, 130, 40);

        jug8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jugelegido.png"))); // NOI18N
        jug8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jug8);
        jug8.setBounds(500, 120, 130, 40);

        jug9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jugelegido.png"))); // NOI18N
        jug9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jug9);
        jug9.setBounds(500, 80, 130, 40);

        jug10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jugelegido.png"))); // NOI18N
        jug10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jug10);
        jug10.setBounds(500, 40, 130, 40);

        jug11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jugelegido.png"))); // NOI18N
        jug11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jug11);
        jug11.setBounds(500, 0, 130, 40);

        txtCanchita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/formacion.png"))); // NOI18N
        txtCanchita.setAutoscrolls(true);
        jPanel2.add(txtCanchita);
        txtCanchita.setBounds(0, -10, 500, 550);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 540, 530));

        btPlantilla.setText("Mandar jugador a la plantilla");
        btPlantilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPlantillaActionPerformed(evt);
            }
        });
        getContentPane().add(btPlantilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 630, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            Grafico grafico= new Grafico();
            grafico.setVisible(true);
            this.setVisible(false);
            
           
    }//GEN-LAST:event_jButton1ActionPerformed
       
    private void txtArqueroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArqueroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArqueroActionPerformed

    private void txtDefensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDefensaActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtDefensaActionPerformed

    private void txtMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedioActionPerformed

    private void txtAtaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAtaqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAtaqueActionPerformed

    private void jsH1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsH1StateChanged
        // TODO add your handling code here:
                txtArquero.setText(String.valueOf(jsH1.getValue()));        
    }//GEN-LAST:event_jsH1StateChanged

    private void jsH2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsH2StateChanged
        // TODO add your handling code here:
                txtDefensa.setText(String.valueOf(jsH2.getValue()));          
    }//GEN-LAST:event_jsH2StateChanged

    private void jsH3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsH3StateChanged
                txtMedio.setText(String.valueOf(jsH3.getValue()));  
    }//GEN-LAST:event_jsH3StateChanged

    private void jsH4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jsH4StateChanged
                txtAtaque.setText(String.valueOf(jsH4.getValue()));  
    }//GEN-LAST:event_jsH4StateChanged

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed


// TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEquipoActionPerformed

    }//GEN-LAST:event_txtNombreEquipoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        Grafico formacion= new Grafico();
        formacion.setVisible(true);
        this.setVisible(false);
        formacion.setLocationRelativeTo(null);
        try {
            enviarEquipo();
        } catch (Exception ex) {
            Logger.getLogger(Nueva.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btGuardarActionPerformed

    private void btPlantillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPlantillaActionPerformed
    EquiposDB db =new EquiposDB() ;
        //db.insertInventario(null, null, roo, roo, roo, roo);

                try {
            //createTable();
            db =new EquiposDB();
        } catch (Exception ex) {
            Logger.getLogger(Grafico.class.getName()).log(Level.SEVERE, null, ex);
        }

           
        
        
        try {
            nteam = txtNombreEquipo.getText();
            String foo = txtNombre.getText();
            comp.get(cont).setLocation(jugElegido.getX(), jugElegido.getY());
            comp.get(cont).setText(foo);
            cont++;
            al();
            pp.CrearPlantilla();
            enviarPlantila();

            
            
        } catch (Exception ex) {
            Logger.getLogger(Nueva.class.getName()).log(Level.SEVERE, null, ex);
        }

        clean();

    }//GEN-LAST:event_btPlantillaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() { 
           public void run() {                
               new Nueva().setVisible(true);
          }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btPlantilla;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider jsH1;
    private javax.swing.JSlider jsH2;
    private javax.swing.JSlider jsH3;
    private javax.swing.JSlider jsH4;
    private javax.swing.JLabel jug1;
    private javax.swing.JLabel jug10;
    private javax.swing.JLabel jug11;
    private javax.swing.JLabel jug2;
    private javax.swing.JLabel jug3;
    private javax.swing.JLabel jug4;
    private javax.swing.JLabel jug5;
    private javax.swing.JLabel jug6;
    private javax.swing.JLabel jug7;
    private javax.swing.JLabel jug8;
    private javax.swing.JLabel jug9;
    private javax.swing.JLabel jugElegido;
    private javax.swing.JTextField txtArquero;
    private javax.swing.JTextField txtAtaque;
    private javax.swing.JLabel txtCanchita;
    private javax.swing.JTextField txtDefensa;
    private javax.swing.JLabel txtH1;
    private javax.swing.JLabel txtH2;
    private javax.swing.JLabel txtH3;
    private javax.swing.JLabel txtH4;
    private javax.swing.JTextField txtMedio;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreEquipo;
    // End of variables declaration//GEN-END:variables
   
    private void clean() {
        this.txtArquero.setText("0");
        this.txtDefensa.setText("0");
        this.txtAtaque.setText("0");
        this.txtMedio.setText("0");
        this.txtNombre.setText("");
        this.jsH1.setValue(0);
        this.jsH2.setValue(0);
        this.jsH3.setValue(0);
        this.jsH4.setValue(0);
    }
    private void enviarPlantila() throws Exception{
        String nom,posP; 
        int arq,def,med,ata, posX, posY,id;
            nom = txtNombre.getText();
            arq = jsH1.getValue();
            def = jsH2.getValue();
            med = jsH3.getValue();
            ata = jsH4.getValue();
            
            posX = jugElegido.getX();
            posY = jugElegido.getY();
            if (posY > 408) {
                posP = "Arquero";
                formAr++;
                promAr = promAr + jsH1.getValue();
            }else if(posY > 286){
                posP = "Defensor";
                promDef = promDef + jsH2.getValue();
                formDef++;
            }else if(posY > 146){
                posP = "Mediocampista";
                promMed = promMed + jsH3.getValue();
                formMed++;
            }else if (posY>119){
                posP="Delantero";
                promAta = promAta + jsH4.getValue();
                formAta++;
                System.out.println(posY);
            }else{
                posP="Delantero";
                promAta = promAta + jsH4.getValue();
                formAta++;
            } 
            
            try {
            pp.insertarPlantilla(nom, posP, promAr, promDef, promMed, promAta, posX, posY);
            } catch (ClassNotFoundException ex) {
            Logger.getLogger(Nueva.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
            Logger.getLogger(Nueva.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

 
    private void enviarEquipo() throws Exception{
            String nombre = txtNombreEquipo.getText();
            String form =  formDef +"-"+formMed +"-"+formAta;
               EquiposDB db =new EquiposDB() ;
        try {
            promMed=promMed/formMed;
            promDef=promDef/formDef;
            promAta=promAta/formAta;
            db.insertarEquipo(nombre, form, promAr, promDef, promMed, promAta);           
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Nueva.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Nueva.class.getName()).log(Level.SEVERE, null, ex);
        }            
    }

    private void al(){
            String nombre = txtNombreEquipo.getText();
            String form =  formDef +"-"+formMed +"-"+formAta;
    }
    
}